(executable ; driver to test minirukaml using ocaml compiler
 (name run_ocaml)
 (modules run_ocaml)
 (libraries stdio base minirukaml))

(library
 (name minirukaml)
 (modules minirukaml)
 (libraries ppx_deriving.runtime base)
 (preprocess
  (pps ppx_deriving.show)))

(cram
 (deps
  %{project_root}/driver/driver.exe
  %{project_root}/tests/minirukaml/run_ocaml.exe
  (glob_files %{project_root}/tests/minirukaml/*.ml)))
