let tests =
  [ "anon1", "../rv64/anon1"
  ; "empty", "../rv64/empty"
  ; "fac", "../rv64/fac"
  ; "fac_acc", "../rv64/fac_acc"
  ; "fac_cps", "../rv64/fac_cps"
  ; "fib_cps", "../rv64/fib_cps"
  ; "fib", "../rv64/fib"
  ; "fib_acc", "../rv64/fib_acc"
  ; "nikita2", "../rv64/nikita2"
  ; "nikita3", "../rv64/nikita3"
  ; "order1", "../rv64/order1"
  ; "pass_print", "../rv64/pass_print"
  ; "dead_print", "dead_print"
  ; "caa_print_order", "caa_print_order"
  ; "caa_print_order_rec", "caa_print_order_rec"
  ]
;;

type mode =
  | CPSOff
  | CPSOn
  | CallArOn

let () =
  let pp1 ~mode ppf name suf path =
    Format.fprintf
      ppf
      {|
(rule
 (targets %s_%s.s)
 (deps
  (:src %s.ml))
 ;  (mode
 ;   (promote (until-clean)))
 (action
  (progn
   (run
    %%{project_root}/back_rv64/RV64_compiler.exe
    -o
    %%{targets}
    %s))))
|}
      name
      suf
      path
    @@
    match mode with
    | CPSOff -> "--no-start\n    %{src}"
    | CPSOn -> "-cps\n    --no-start\n    %{src}"
    | CallArOn -> "-cps\n    -call_arity\n    --no-start\n    %{src}"
  in
  let pp2 ppf name =
    Format.fprintf
      ppf
      {|
(rule
 (targets %s.exe)
 (deps
  %%{project_root}/back_rv64/RV64_compiler.exe
  (:src %s.s)
  %%{project_root}/back_rv64/rukaml_stdlib.o)
 ;(mode
 ; (promote (until-clean)))
 (action
  (progn
   (run riscv64-linux-gnu-gcc-13 -g -c %%{src} -o %s.o)
   (run
    riscv64-linux-gnu-gcc-13
    -g
    %%{project_root}/back_rv64/rukaml_stdlib.o
    %s.o
    -o
    %%{targets}))))
|}
      name
      name
      name
      name
  in
  Out_channel.with_open_text "dune.tests" (fun ch ->
    let ppf = Format.formatter_of_out_channel ch in
    Format.fprintf ppf "; This file was autogenerated by 'ocaml gen.ml'\n";
    ListLabels.iter tests ~f:(fun (name, mlpath) ->
      Format.fprintf ppf "\n;;; %s\n\n" name;
      pp1 ppf name "cpsoff" mlpath ~mode:CPSOff;
      pp1 ppf name "cpson" mlpath ~mode:CPSOn;
      pp1 ppf name "callaron" mlpath ~mode:CallArOn;
      pp2 ppf (name ^ "_cpsoff");
      pp2 ppf (name ^ "_cpson");
      pp2 ppf (name ^ "_callaron");
      Format.fprintf
        ppf
        {|
(cram
 (applies_to %s)
 (deps
  %%{project_root}/back_rv64/rukaml_stdlib.o
  %s.ml
  %s_cpsoff.exe
  %s_cpson.exe
  %s_callaron.exe
  ;
  ))
  |}
        name
        mlpath
        name
        name
        name;
      Out_channel.with_open_text (name ^ ".t") (fun ch ->
        Printf.fprintf
          ch
          "  $ qemu-riscv64 -L /usr/riscv64-linux-gnu -cpu rv64  ./%s_cpsoff.exe\n\n"
          name;
        Printf.fprintf
          ch
          "  $ qemu-riscv64 -L /usr/riscv64-linux-gnu -cpu rv64  ./%s_cpson.exe\n\n"
          name;
        Printf.fprintf
          ch
          "  $ qemu-riscv64 -L /usr/riscv64-linux-gnu -cpu rv64  ./%s_callaron.exe\n\n"
          name;
        flush ch);
      Format.pp_print_flush ppf ()))
;;
