name: Build master

on:
  push:
    branches:
      - "riscv64"

env:
  OPAMROOT: /home/opam/.opam

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kakadu18/ocaml:llvm # TODO: add dune-site to image
      options: --user root

    # The below probably could be used instead of styfle/cancel-workflow-action
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

    steps:
      - run: opam --version
      - run: opam exec -- ocamlopt --version
      - run: opam list

      #- name: Cancel Previous Runs
      #  uses: styfle/cancel-workflow-action@0.11.0
      #  with:
      #    access_token: ${{ github.token }}

      # checking out the code seems to be important because local switch is used
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: riscv64
          show-progress: false

      - name: Install OPAM dependencies via Makefile
        #continue-on-error: true
        run: |
          sudo apt update --yes
          make deps

      - run: opam exec -- dune build @default --profile=release
      - run: opam exec -- dune test
